name: mqtt_client
description: A Dart MQTT5 subscriber client for receiving messages from Mosquitto broker
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  # MQTT client library with MQTT5 support
  mqtt5_client: ^4.12.2
  typed_data: ^1.4.0

  # Command line argument parsing
  args: ^2.7.0

  # Logging utilities
  logging: ^1.3.0

  # For graceful shutdown handling
  # Note: dart:io provides ProcessSignal for signal handling

dev_dependencies:
  # Linting and analysis
  lints: ^6.0.0

  # Testing
  test: ^1.26.2

# Executable configuration
executables:
  mqtt_subscriber: main